### ISSUE TITLE
nvidia binary file that works with rhel7 branch

### ISSUE THREAD

**Issue by EmilyStacy** [NVIDIA/yum-packaging-nvidia-driver#1]
Hi, does anyone know the matching NVIDIA-Linux-x86_64-470.94.run file for the rhel7 branch? The one we are using now created errors about missing powered. Thanks!

**Comment by kmittman** [comment]
Hi @EmilyStacy 
Please use the `470-rhel7` git branch for packaging 470.xx drivers on RHEL7-like distros.

IIRC the _nvidia-powerd_ files were introduced in the 510.xx drivers. It looks like when I pushed the latest changes to GitHub, I accidentally branched "virtual" `rhel7` branch from `510` (meant for Fedora/RHEL8-like). I will fix those virtual branches shortly.

**Comment by EmilyStacy** [comment]
awesome, thanks a lot! Now the error makes much more sense:
 + install -p -m 0755 nvidia-powerd /root/nvidia-driver/BUILDROOT/nvidia-driver-470.94-1.el7.x86_64/usr/bin
#29 395.8 install: cannot stat 'nvidia-powerd': No such file or directory
#29 395.8 error: Bad exit status from /var/tmp/rpm-tmp.N1ZfkK (%install)
#29 395.8     Bad exit status from /var/tmp/rpm-tmp.N1ZfkK (%install)
#29 395.8 
#29 395.8 
#29 395.8 RPM build errors:
#29 395.8 
#29 395.8 ERROR: at line `rpmbuild --define '%_topdir /root/nvidia-driver' --define 'debug_package %{nil}' --define 'version 470.94' --define 'driver_branch latest-dkms' --define 'is_dkms 1' --define 'is_latest 1' --define '_unpackaged_files_terminate_build 0' --define 'epoch 3' --target x86_64 -v -bb SPECS/nvidia-driver.spec
