### ISSUE TITLE
Missing symlink “nvidia-drm_gbm.so” in Fedora driver package. Necessary for Wayland.

### ISSUE THREAD

**Issue by JoeHannes90** [NVIDIA/yum-packaging-nvidia-driver#4]
Hi.

I’m using the official Nvidia Cuda [Repostory](https://developer.download.nvidia.com/compute/cuda/repos/fedora35/x86_64/) for Fedora to install both, the cuda toolkit and the nvidia driver. It works fine but the driver packages are missing a symlink that should be there since v495 (see [release notes](https://www.nvidia.com/Download/driverResults.aspx/184429/), first highlight). The symlink should be /usr/lib64/gbm/nvidia-drm_gbm.so → /usr/lib64/libnvidia-allocator.so.VERSION (or -> ../libnvidia-allocator.so.VERSION).

Without this symlink Wayland session does not start at all.

I created the symlink manually, but it would be nice if it was already in the package, unless there is a reason why it is not the case. The hard part of fixing the issue was finding out that the symlink was missing at all.

I don't know if this issues is also present in the RHEL 8 Repo.

I've also posted the issue at in the [Forum](https://forums.developer.nvidia.com/t/missing-symlink-nvidia-drm-gbm-so-in-fedora-driver-package-necessary-for-wayland/215948) but I found this github page later, which I think is the right place to post it.

Thank you in advance

**Comment by kmittman** [comment]
Hi @JoeHannes90 
Thank you for reporting this. It will be fixed in the *next* NVIDIA driver version package release from `515` branch for Fedora, RHEL8, and RHEL7 in the CUDA repository. Specifically in the `nvidia-driver-libs` RPM, here is a snippet of the `.spec`

```
diff --git a/nvidia-driver.spec b/nvidia-driver.spec
@@ -252,6 +252,7 @@
+mkdir -p %{buildroot}%{_datadir}/egl/egl_external_platform.d/
 
@@ -339,6 +340,13 @@
+# GBM files
+%ifnarch %{ix86}
+install -p -m 0644 15_nvidia_gbm.json %{buildroot}%{_datadir}/egl/egl_external_platform.d/
+mkdir -p %{buildroot}%{_libdir}/gbm/
+ln -sf %{_libdir}/libnvidia-allocator.so.1 %{buildroot}%{_libdir}/gbm/nvidia-drm_gbm.so
+%endif
+
@@ -523,6 +531,10 @@
+%{_libdir}/libnvidia-egl-gbm.so.1
+%{_libdir}/libnvidia-egl-gbm.so.1.1.0
+%{_libdir}/gbm/nvidia-drm_gbm.so
+%{_datadir}/egl/egl_external_platform.d/15_nvidia_gbm.json
```
```
diff --git a/nvidia-generate-tarballs-aarch64.sh b/nvidia-generate-tarballs-aarch64.sh
@@ -37,7 +37,6 @@
-        libnvidia-egl-gbm.so.* \
```
``` 
diff --git a/nvidia-generate-tarballs-ppc64le.sh b/nvidia-generate-tarballs-ppc64le.sh
@@ -37,7 +37,6 @@
-        libnvidia-egl-gbm.so.* \
```
```
diff --git a/nvidia-generate-tarballs.sh b/nvidia-generate-tarballs.sh
@@ -25,7 +25,6 @@
-    libnvidia-egl-gbm.so.* \
```

**Comment by JoeHannes90** [comment]
Hi @kmittman,

Thanks you very much for the quick fix. I look forward to the release of the next driver version.

**Comment by JoeHannes90** [comment]
Hi,
I can confirm that the files are present in version 515.48.07 and the issue is solved.
Thank you, again!
