### ISSUE TITLE
please build for fedora37

### ISSUE THREAD

**Issue by cathaysia** [NVIDIA/yum-packaging-nvidia-driver#6]
I had noticed there has no repo for fedora37, can you support it?

**Comment by kmittman** [comment]
Hi @cathaysia I've moved this issue to a more appropriate project for tracking.
RPM packages targeting Fedora 37 in the CUDA repo are planned for a future release.
Thank you for your patience.

**Comment by cathaysia** [comment]
thanks :)

**Comment by kmittman** [comment]
Fedora 37 repository is now available: https://developer.download.nvidia.com/compute/cuda/repos/fedora37/x86_64/
- CUDA toolkit `12.0.1`
- NVIDIA driver `525.85.12`

**Comment by cathaysia** [comment]
Congratulations :)
________________________________
