### ISSUE TITLE
libnvidia-ml.so link to lib64 was removed causing failures since 560

### ISSUE THREAD

**Issue by talbdev** [NVIDIA/yum-packaging-nvidia-driver#9]
Hi,

There was a "major rework" on the `nvidia-driver.spec` file which can be seen here: https://github.com/NVIDIA/yum-packaging-nvidia-driver/commit/d54fc9a8ec536dbfbbc09c6f23dfd5d89e4572f7#diff-9eacf29a7bb5f39261f8b4eb45596452ded7911a0aa890f646504c14b719d41bL235

This major rework was part of driver 560+

One of the changes removed the the following in line 235:
`ln -sf libnvidia-ml.so.%{version}               libnvidia-ml.so`

Now applications like slurm for example expects to find this so in lib64 and they can't(can be seen [here ](https://github.com/SchedMD/slurm/blob/master/src/interfaces/gpu.c#L98) plain simple dlopen). Any special reason to remove this link ?

**Comment by dev-ninja-ops** [comment]
It appears that SLURM has addressed the issue by adding a mitigation that checks for the presence of libnvidia-ml.so.1 and then loads it if available, as seen in this commit: [here](https://github.com/SchedMD/slurm/commit/12cea079f4b5077e6e7d35b72e99b51a562bc8e2)

However, it's still puzzling why the libnvidia-ml.so symlink was removed from lib64, as this could disrupt other applications that rely on it.

**Comment by scaronni-nvidia** [comment]
Hello,

the approach of loading `libnvidia-ml.so.1` is the correct approach. The unversioned library should be used only for linking building against it.

In the previous driver versions, there was in fact an `nvidia-driver-devel` subpackage which contained the unversioned `libnvidia-ml.so` library. But that was a mistake, as the package could not really be used as the unversioned libraries contained therein did not have any header for compiling against them and it was a leftover.

The few remaining unversioned libraries that are required in the driver have been moved to the main library packages.

Regarding NVML, the NVML stub and the headers are in the `cuda-nvml-devel` package, so if you need to link to it that's what should be installed.

```
$ rpm -qpl cuda-nvml-devel-12-6-12.6.77-1.x86_64.rpm | grep targets
/usr/local/cuda-12.6/targets
/usr/local/cuda-12.6/targets/x86_64-linux
/usr/local/cuda-12.6/targets/x86_64-linux/include
/usr/local/cuda-12.6/targets/x86_64-linux/include/nvml.h
/usr/local/cuda-12.6/targets/x86_64-linux/lib
/usr/local/cuda-12.6/targets/x86_64-linux/lib/stubs
/usr/local/cuda-12.6/targets/x86_64-linux/lib/stubs/libnvidia-ml.a
/usr/local/cuda-12.6/targets/x86_64-linux/lib/stubs/libnvidia-ml.so
```

Again, please stick to loading `libnvidia-ml.so.1` which is the correct approach. Thanks.
